# Generated by Django 6.0.4 on 2026-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(default='Van', max_length=100)),
                ('license_plate', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('dropoff_address', models.TextField()),
                ('package_details', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned (Pending Pickup)'), ('PICKED_UP', 'Picked Up (In Transit)'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
