# Generated by Django 6.0.4 on 2026-04-18 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('service', '0003_partorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypartnerprofile',
            old_name='vehicle_number',
            new_name='license_plate',
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='vehicle_type',
            field=models.CharField(default='Van', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypartnerprofile',
            name='assigned_service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicecenter'),
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('dropoff_address', models.TextField()),
                ('package_details', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned (Pending Pickup)'), ('PICKED_UP', 'Picked Up (In Transit)'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delivery.deliverypartnerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
