# Generated by Django 6.0.4 on 2026-04-18 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecenter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='owner.vehicle')),
            ],
        ),
    ]
