# Generated by Django 6.0.4 on 2026-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='part_name',
            field=models.CharField(default='Unknown Part', max_length=100),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
