# Generated by Django 6.0.4 on 2026-04-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_warrantyclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('SHIPPED', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecenter')),
            ],
        ),
    ]
