# Generated by Django 6.0.4 on 2026-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='is_dynamic_pricing',
            field=models.BooleanField(default=False, help_text='Enable automatic surge pricing during peak hours'),
        ),
    ]
